# Generated by Django 5.0.8 on 2024-10-09 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0033_alter_rooms_room_name'),
        ('institutes', '0002_alter_institutes_acronym_and_more'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSchedulerData',
            fields=[
                ('final_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_data_json_file', models.FileField(upload_to='scheduler_data/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Final Scheduler Data',
                'verbose_name_plural': 'Final Scheduler Data',
                'db_table': 'final_scheduler_data',
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitialSchedulerData',
            fields=[
                ('scheduler_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Pending'), (3, 'Processing'), (4, 'Completed'), (5, 'Error'), (6, 'Cancelled')], default=2)),
                ('initial_data_json_file', models.FileField(blank=True, null=True, upload_to='scheduler_data/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('final_data_json_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.finalschedulerdata')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs')),
            ],
            options={
                'verbose_name': 'Initial Scheduler Data',
                'verbose_name_plural': 'Initial Scheduler Data',
                'db_table': 'initial_scheduler_data',
            },
        ),
        migrations.AddConstraint(
            model_name='initialschedulerdata',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [2, 3])), fields=('institute', 'program', 'semester'), name='unique_active_processing_per_institute_program_semester'),
        ),
    ]
