# Generated by Django 4.2.11 on 2024-07-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('is_lab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'Versions',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('lecture', models.IntegerField(default=0)),
                ('laboratory', models.IntegerField(default=0)),
                ('credit_units', models.IntegerField(default=0)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lab', models.BooleanField(default=False)),
                ('year_level', models.IntegerField(default=1)),
                ('is_major_course', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.versions')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
    ]
