# Generated by Django 5.0.4 on 2024-08-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('institutes', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='institutes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes'),
            preserve_default=False,
        ),
    ]
