# Generated by Django 5.0.4 on 2024-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_programs_institutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='institutes',
            new_name='institute',
        ),
    ]
