# Generated by Django 5.0.7 on 2024-08-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_institutes_programs_institute'),
    ]

    operations = [
    ]
