# Generated by Django 5.0.7 on 2024-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_populate_program_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='program_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
