# Generated by Django 5.0.7 on 2024-08-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_programs_program_slug'),
    ]

    operations = [
    ]
