# Generated by Django 5.0.7 on 2024-08-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_programs_program_slug'),
    ]

    operations = [
    ]
