# Generated by Django 5.0.7 on 2024-08-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_populate_program_slugs'),
    ]

    operations = [
    ]
