# Generated by Django 5.0.7 on 2024-08-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_populate_program_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumYear',
            fields=[
                ('curriculum_id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum_year', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curriculum Year',
                'verbose_name_plural': 'Curriculum Year',
                'db_table': 'curriculum_year',
            },
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='versions',
            table='versions',
        ),
        migrations.AddField(
            model_name='courses',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumyear'),
            preserve_default=False,
        ),
    ]
