# Generated by Django 5.0.7 on 2024-08-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_curriculumyear_alter_rooms_table_and_more'),
    ]

    operations = [
    ]
