# Generated by Django 5.0.7 on 2024-08-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_auto_20240808_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='curriculum',
        ),
        migrations.DeleteModel(
            name='CurriculumYear',
        ),
    ]
