# Generated by Django 5.0.7 on 2024-08-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_rooms_table_alter_versions_table'),
        ('curriculum', '0014_remove_programs_curriculum_remove_courses_curriculum_and_more'),
    ]

    operations = [
    ]
