# Generated by Django 5.0.7 on 2024-08-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_merge_20240808_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Versions',
            new_name='CurriculumYear',
        ),
        migrations.AlterModelOptions(
            name='curriculumyear',
            options={'verbose_name': 'Curriculum Year', 'verbose_name_plural': 'Curriculum Year'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='version',
            new_name='curriculum',
        ),
        migrations.RenameField(
            model_name='curriculumyear',
            old_name='version_id',
            new_name='curriculum_id',
        ),
        migrations.RenameField(
            model_name='curriculumyear',
            old_name='version_name',
            new_name='curriculum_year',
        ),
        migrations.AddField(
            model_name='programs',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumyear'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='curriculumyear',
            table='curriculum_year',
        ),
    ]
