# Generated by Django 5.0.7 on 2024-08-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_rename_versions_curriculumyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='is_major_course',
        ),
    ]
