# Generated by Django 5.0.7 on 2024-08-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_remove_programs_curriculum_curriculumyear_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='program',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
    ]
