# Generated by Django 5.0.7 on 2024-08-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_alter_programs_program_slug'),
    ]

    operations = [
    ]
