# Generated by Django 5.0.7 on 2024-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_auto_20240824_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
