# Generated by Django 5.0.8 on 2024-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_alter_programs_program_slug'),
        ('institutes', '0002_alter_institutes_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='curriculumyear',
            constraint=models.UniqueConstraint(fields=('curriculum_year', 'institute', 'program'), name='unique_curriculum_year_institute_program'),
        ),
    ]
