# Generated by Django 5.0.4 on 2024-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_alter_programs_program_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
