# Generated by Django 5.0.4 on 2024-09-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_rooms_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AddField(
            model_name='rooms',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
