# Generated by Django 5.0.8 on 2024-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_alter_rooms_options_rooms_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
