# Generated by Django 4.2.11 on 2024-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.IntegerField(blank=True, choices=[(1, 'Institute of Computing'), (2, 'Institute of Aquatic and Applied Sciences'), (3, 'Institute of Leadership, Entrepreneurship and Good Governance'), (4, 'Institute of Teacher Education')], null=True),
        ),
    ]
