# Generated by Django 4.2.11 on 2024-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Faculty and Staff', 'verbose_name_plural': 'Faculty and Staff'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'vpaa'), (3, 'dean'), (4, 'progchair'), (5, 'faculty'), (6, 'student')], default=5),
        ),
    ]
