# Generated by Django 4.2.11 on 2024-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/profile_imagesdefault-avatar.jpg', upload_to='profile_images/'),
        ),
    ]
