# Generated by Django 4.2.11 on 2024-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(default='cover_image/default-cover.jpg', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default-avatar.jpg', upload_to='profile_image/'),
        ),
    ]
