# Generated by Django 4.2.11 on 2024-07-26 15:01

import apps.user.common.phone_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_cover_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a phone number in the format: 09XXXXXYYYY', max_length=11, null=True, validators=[apps.user.common.phone_validators.validate_ph_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default-profile.png', upload_to='profile_image/'),
        ),
    ]
