# Generated by Django 4.2.11 on 2024-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
