# Generated by Django 5.0.7 on 2024-07-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
