# Generated by Django 5.0.7 on 2024-07-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
