# Generated by Django 5.0.4 on 2024-08-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('institutes', '__first__'),
        ('user', '0016_delete_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institute',
        ),
        migrations.AddField(
            model_name='user',
            name='institutes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.IntegerField(choices=[(1, 'Permanent'), (2, 'Temporary'), (3, 'Casual'), (4, 'Contract of Service'), (5, 'Job Order'), (6, 'Coterminous'), (7, 'Contractual')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(1, 'Instructor I'), (2, 'Instructor II'), (3, 'Instructor III'), (4, 'Assistant Professor I'), (5, 'Assistant Professor II'), (6, 'Assistant Professor III'), (7, 'Assistant Professor IV'), (8, 'Associate Professor I'), (9, 'Associate Professor II'), (10, 'Associate Professor III'), (11, 'Associate Professor IV'), (12, 'Professor I'), (13, 'Professor II'), (14, 'Professor III'), (15, 'Professor IV'), (16, 'Professor V'), (17, 'Professor VI'), (18, 'College Professor')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default-avatar.jpg', upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
    ]
