# Generated by Django 5.0.4 on 2024-08-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_user_institute_user_institutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='institutes',
            new_name='institute',
        ),
    ]
