# Generated by Django 5.0.7 on 2024-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_institutes_user_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Permanent'), (2, 'Temporary'), (3, 'Casual'), (4, 'Contract of Service'), (5, 'Job Order'), (6, 'Coterminous'), (7, 'Contractual')], null=True),
        ),
    ]
