# Generated by Django 5.0.8 on 2024-09-06 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_alter_programs_program_slug_and_more'),
        ('institutes', '0002_alter_institutes_acronym_and_more'),
        ('user', '0022_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'db_table': 'user_groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.courses')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'db_table': 'group_members',
            },
        ),
    ]
