# Generated by Django 5.0.8 on 2024-09-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_alter_programs_program_slug_and_more'),
        ('user', '0024_alter_groupmember_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddField(
            model_name='groupmember',
            name='courses',
            field=models.ManyToManyField(to='curriculum.courses'),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='course',
        ),
    ]
