# Generated by Django 5.0.8 on 2024-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_groupmember_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='date_assigned',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
