# Generated by Django 5.0.8 on 2024-09-09 17:55

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_groupmember_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=apps.user.common.account_compress_image.ProfileImageField(upload_to='profile_images/'),
        ),
    ]
