# Generated by Django 5.0.8 on 2024-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_alter_rooms_room_name'),
        ('institutes', '0002_alter_institutes_acronym_and_more'),
        ('user', '0032_alter_usergroup_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('group_name', 'program', 'institute', 'semester')},
        ),
    ]
