# Generated by Django 5.0.8 on 2024-09-11 15:23

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_usergroup_unique_together_usergroup_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/111092024231832.jpg', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=apps.user.common.account_compress_image.ProfileImageField(default='profile_image/111092024231952.jpg', upload_to='profile_image/'),
        ),
    ]
