# Generated by Django 5.0.8 on 2024-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_usergroup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(1, 'Instructor I'), (2, 'Instructor II'), (3, 'Instructor III'), (4, 'Assistant Professor I'), (5, 'Assistant Professor II'), (6, 'Assistant Professor III'), (7, 'Assistant Professor IV'), (8, 'Associate Professor I'), (9, 'Associate Professor II'), (10, 'Associate Professor III'), (11, 'Associate Professor IV'), (12, 'Associate Professor V'), (13, 'Professor I'), (14, 'Professor II'), (15, 'Professor III'), (16, 'Professor IV'), (17, 'Professor V'), (18, 'Professor VI'), (19, 'College Professor')], null=True),
        ),
    ]
