# Generated by Django 5.0.8 on 2024-10-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_user_position'),
    ]

    operations = [
    ]
