# Generated by Django 5.0.8 on 2024-10-10 10:42

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(blank=True, null=True, upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=apps.user.common.account_compress_image.ProfileImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
