# Generated by Django 5.0.8 on 2024-10-10 10:43

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_user_cover_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/111092024231832.jpg', upload_to='cover_image/'),
        ),
    ]
