# Generated by Django 5.0.7 on 2024-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutes',
            name='acronym',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='institute_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='institute_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
